### ISSUE TITLE
web viewer doesn't refresh PDF

### ISSUE THREAD

**Issue by Aazhar** [DARIAH-ERIC/DESIR-CodeSprint-TrackA-TextMining#1]
Submitting new pdf doesn't clear the previous one.

**Comment by lfoppiano** [comment]
is this fixed? @ltadjou

**Comment by tantikristanti** [comment]
I have tested this issue and it has been fixed. So, I think we can close this one.

**Comment by tantikristanti** [comment]
It can be re-opened if the same problem arises.
